CREATE TABLE [dbo].[Submissions]
(
	[SubmissionId] INT IDENTITY(1,1) NOT NULL,
	[DateSubmitted] DATETIMEOFFSET(0) DEFAULT SYSDATETIMEOFFSET() NOT NULL,
	[IsAwarded] BIT NOT NULL DEFAULT 0,
	[UserId] INT NOT NULL,
	[UploadId] INT NOT NULL,
	[JobId] INT NOT NULL,
    PRIMARY KEY ([SubmissionId]),
	FOREIGN KEY ([UserId]) REFERENCES [dbo].[Users]([UserId]) ON DELETE NO ACTION ON UPDATE CASCADE,
	FOREIGN KEY ([UploadId]) REFERENCES [dbo].[Uploads]([UploadId]) ON DELETE NO ACTION ON UPDATE CASCADE,
	FOREIGN KEY ([JobId]) REFERENCES [dbo].[Jobs]([JobId]) ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT CK_Submissions_Unique_UploadId UNIQUE([UploadId])
)
