CREATE TABLE [dbo].[Submissions]
(
	[SubmissionId] INT IDENTITY(1,1) NOT NULL,
	[DateSubmitted] DATETIMEOFFSET(0) DEFAULT SYSDATETIMEOFFSET() NOT NULL,
	[IsAwarded] BIT NOT NULL DEFAULT 0,
	[UserId] INT NOT NULL,
	[FileId] INT NOT NULL,
	[JobId] INT NOT NULL,
    PRIMARY KEY ([SubmissionId]),
	FOREIGN KEY ([UserId]) REFERENCES [dbo].[Users]([UserId]) ON DELETE NO ACTION ON UPDATE CASCADE,
	FOREIGN KEY ([FileId]) REFERENCES [dbo].[Files]([FileId]) ON DELETE NO ACTION ON UPDATE CASCADE,
	FOREIGN KEY ([JobId]) REFERENCES [dbo].[Jobs]([JobId]) ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT UNIQUE_FILEID_SUBMISSIONS UNIQUE([FileId])
)
