CREATE TABLE [dbo].[Files]
(
	[FileId] INT IDENTITY(1,1) NOT NULL, 
    [FileData] VARBINARY(MAX) FILESTREAM NULL, 
    [RowGuid] UNIQUEIDENTIFIER ROWGUIDCOL UNIQUE DEFAULT NEWID() NOT NULL,
	PRIMARY KEY ([FileId])
)
