//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslatoWebsite.ServiceLoginUser {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceLoginUser.IServiceLoginUser")]
    public interface IServiceLoginUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoginUser/loginUser", ReplyAction="http://tempuri.org/IServiceLoginUser/loginUserResponse")]
        bool loginUser(string userNameOrEmail, string HRpassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoginUser/loginUser", ReplyAction="http://tempuri.org/IServiceLoginUser/loginUserResponse")]
        System.Threading.Tasks.Task<bool> loginUserAsync(string userNameOrEmail, string HRpassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceLoginUserChannel : TranslatoWebsite.ServiceLoginUser.IServiceLoginUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceLoginUserClient : System.ServiceModel.ClientBase<TranslatoWebsite.ServiceLoginUser.IServiceLoginUser>, TranslatoWebsite.ServiceLoginUser.IServiceLoginUser {
        
        public ServiceLoginUserClient() {
        }
        
        public ServiceLoginUserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceLoginUserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLoginUserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLoginUserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool loginUser(string userNameOrEmail, string HRpassword) {
            return base.Channel.loginUser(userNameOrEmail, HRpassword);
        }
        
        public System.Threading.Tasks.Task<bool> loginUserAsync(string userNameOrEmail, string HRpassword) {
            return base.Channel.loginUserAsync(userNameOrEmail, HRpassword);
        }
    }
}
