//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslatoDevWebsite.ServiceLoginUser {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceLoginUser.ReturnedObject", Namespace="http://schemas.datacontract.org/2004/07/TranslatoServiceLibrary.SRV")]
    [System.SerializableAttribute()]
    public partial class ServiceLoginUserReturnedObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                if ((this.codeField.Equals(value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceLoginUser.IServiceLoginUser")]
    public interface IServiceLoginUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoginUser/loginUser", ReplyAction="http://tempuri.org/IServiceLoginUser/loginUserResponse")]
        TranslatoDevWebsite.ServiceLoginUser.ServiceLoginUserReturnedObject loginUser(string publicKey, string privateKey, string userNameOrEmail, string HRpassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoginUser/loginUser", ReplyAction="http://tempuri.org/IServiceLoginUser/loginUserResponse")]
        System.Threading.Tasks.Task<TranslatoDevWebsite.ServiceLoginUser.ServiceLoginUserReturnedObject> loginUserAsync(string publicKey, string privateKey, string userNameOrEmail, string HRpassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceLoginUserChannel : TranslatoDevWebsite.ServiceLoginUser.IServiceLoginUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceLoginUserClient : System.ServiceModel.ClientBase<TranslatoDevWebsite.ServiceLoginUser.IServiceLoginUser>, TranslatoDevWebsite.ServiceLoginUser.IServiceLoginUser {
        
        public ServiceLoginUserClient() {
        }
        
        public ServiceLoginUserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceLoginUserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLoginUserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLoginUserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TranslatoDevWebsite.ServiceLoginUser.ServiceLoginUserReturnedObject loginUser(string publicKey, string privateKey, string userNameOrEmail, string HRpassword) {
            return base.Channel.loginUser(publicKey, privateKey, userNameOrEmail, HRpassword);
        }
        
        public System.Threading.Tasks.Task<TranslatoDevWebsite.ServiceLoginUser.ServiceLoginUserReturnedObject> loginUserAsync(string publicKey, string privateKey, string userNameOrEmail, string HRpassword) {
            return base.Channel.loginUserAsync(publicKey, privateKey, userNameOrEmail, HRpassword);
        }
    }
}
